#Uppdatera systemet
sudo apt update && sudo apt upgrade -y

#Installera Nginx
sudo apt install nginx -y

#Titta om nginx är igång
systemctl status nginx.serivce

#Installera php.
sudo apt install php-fpm php-common php-mysql php-xml php-snmp php-intl php-curl php-gd php-imagick php-cli php-dev php-imap php-mbstring php-opcache php-redis php-soap php-zip -y

#Installera MariaDB
sudo apt install mariadb-server -y
sudo systemctl start mariadb
sudo systemctl enable mariadb
systemctl status mariadb
sudo mysql_secure_installation
sudo mariadb -u root
CREATE DATABASE wpdb;
CREATE USER 'wpuser'@'localhost' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wpdb.* TO 'wpuser'@'localhost';
FLUSH PRIVILEGES;
EXIT;

#Installera WordPress
cd /var/www/html
sudo wget https://wordpress.org/latest.zip
sudo unzip latest.zip
sudo rm latest.zip
sudo mv wordpress/* .
sudo rmdir wordpress/

#Konfigurera Wordpress

sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
sudo micro /var/www/html/wp-config.php 
#I denna fil måste du skriva in på samma sätt som det står nedan.

#Namnet för databasen för Wordpress
define( 'DB_NAME', 'wpdb' );

Database username

define ('DB_USER', 'wpuser');

Database password

define( 'DB_PASSWORD', '12345' );

Database hostname

define( 'DB_HOST', 'localhost' );

#När du är klar spara och stäng filen.
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

#Konfigurera virtual hosten (NGINX)
sudo micro /etc/nginx/sites-available/default

#Ta bort allt i filen och kopiera in
server {
    listen 80;
    server_name wplocal;
    root /var/www/html;
    index index.php;
    server_tokens off;
    access_log /var/log/nginx/wordpress_access.log;
    error_log /var/log/nginx/wordpress_error.log;
    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi.conf;
    }
}

#Sedan stäng filen
sudo nginx-t
sudo systemctl restart nginx.service

#Gå till din browser 
http://wplocal.localhost

#Installera Wordpress.
